In [5]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [8]:
# default graph에 node로 추가
hello = tf.constant("Hello, TensorFlow!")

# tensorflow 1.x.x는 session을 만들어 run 해야했었지만 2.x.x는 바로 print
tf.print(hello)

Hello, TensorFlow!


# Computational Graph

In [9]:
# node를 만듬(build graph)
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
node3 = tf.add(node1, node2)

In [10]:
# 결과값이 나오지 않음
print("node1:", node1, "node2:", node2)
print("node3", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3 tf.Tensor(7.0, shape=(), dtype=float32)


In [11]:
# 결과값
tf.print([node1, node2])
tf.print(node3)

[3, 4]
7


# Placeholder

In [26]:
# Tensorflow 1.x.x 
# a = tf.placeholder(tf.float32)
# b = tf.placeholder(tf.float32)
#adder _node = a + b

# print(sess.run(adder_node, feed_dict={a: 3, b: 4.5}))
# print(sess.run(adder_node, feed_dict={a: [1,3], b: [2, 4]}))

# Tensorflow 2.x.x

# 함수 정의
@tf.function
def adder(a, b):
    return a + b

A = tf.constant(1)
B = tf.constant(2)
print(adder(A,B))

C = tf.constant([1, 2])
D = tf.constant([3, 4])
print(adder(C, D))

E = tf.constant([[1, 2, 3], [4, 5, 6]])
F = tf.constant([[2, 3, 4], [5, 6, 7]])
print(adder(E, F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)
