In [3]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.4.1'

# Eager Execution(즉시 실행 모드)

Tensorflow 1.x : 는 계산 그래프를 선언하고, 세션을 통해 Tensor를 주고 받으며 계산하는 구조
Tensorflow 2.x : 자동으로 Eager Execution(즉시 실행 모드)가 적용되기 때문에 그래프와 세션을 만들지 않아도 Tensor 값을 계산하고 numpy()함수를 이요하면 파이썬의 numpy 타입으로 변환할 수 있음

In [2]:
# default graph에 node로 추가
hello = tf.constant("Hello, TensorFlow!")

# tensorflow 1.x.x는 session을 만들어 run 해야했었지만 2.x.x는 바로 print
tf.print(hello)

Hello, TensorFlow!


In [4]:
a = tf.constant(10)
b = tf.constant(20)

c = a + b
d = (a+b).numpy() # numpy() 메소드는 numpy 값을 리턴

In [5]:
print(type(c))
print(c)
print(type(d), d)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(30, shape=(), dtype=int32)
<class 'numpy.int32'> 30


In [6]:
# numpy 값을 tensor 값으로 변환
d_numpy_to_tensor = tf.convert_to_tensor(d)

In [7]:
print(type(d_numpy_to_tensor))
print(d_numpy_to_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(30, shape=(), dtype=int32)


# tf.constant()

In [8]:
a = tf.constant(1.0)
b = tf.constant(2.0)

c = a + b

print(c.numpy())

3.0


# tf.Variable()

In [11]:
# 가우시안 분포
W = tf.Variable(tf.random.normal([1]))

print('inital W = ', W.numpy())
print('=======================================================')

# session 생성 없이 즉시 실행
# numpy() 메서드 사용하면 numpy 값을 리턴해줌

for step in range(2):
    W = W + 1.0
    print('step = ', step, ', W = ', W.numpy())

inital W =  [0.43114734]
step =  0 , W =  [1.4311473]
step =  1 , W =  [2.4311473]


# tf.placeholder()

In [12]:
a = tf.constant(1.0)
b = tf.constant(3.0)

# 함수 정의
def tensor_sum(x, y):
    return x + y

result = tensor_sum(a, b)

print(type(result))
print(result.numpy())

<class 'tensorflow.python.framework.ops.EagerTensor'>
4.0


In [9]:
# 함수 정의
@tf.function
def adder(a, b):
    return a + b

A = tf.constant(1)
B = tf.constant(2)
print(adder(A,B))
print(adder(A,B).numpy())

C = tf.constant([1, 2])
D = tf.constant([3, 4])
print(adder(C, D))
print(adder(C, D).numpy())

E = tf.constant([[1, 2, 3], [4, 5, 6]])
F = tf.constant([[2, 3, 4], [5, 6, 7]])
print(adder(E, F))
print(adder(E, F).numpy())

tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor([4 6], shape=(2,), dtype=int32)
[4 6]
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)
[[ 3  5  7]
 [ 9 11 13]]
