In [1]:
# mnist_softmax
# Learning rate and Evaluation
import tensorflow as tf

In [4]:
learning_rate = 0.001
batch_size = 100
training_epochs = 15
nb_classes = 10

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# normalizing data
x_train, x_test = x_train / 255.0, x_test / 255.0

# change data shape
print(x_train.shape)
x_train = x_train.reshape(x_train.shape[0], x_train.shape[1] * x_train.shape[2])
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1] * x_test.shape[2])

# change result to one-hot encoding
# in tf1, one_hot= True in read_data_sets("MNIST_data/", one_hot=True)
# took care of it, but here we need to manually convert them
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

(60000, 28, 28)


In [6]:
# # Consider an array of 5 labels out of a set of 3 classes {0, 1, 2}:
# array([0, 2, 1, 2, 0])
# `to_categorical` converts this into a matrix with as many columns as there are classes. The number of rows
#  stays the same. to_categorical(labels)
# array([[ 1.,  0.,  0.],
#        [ 0.,  0.,  1.],
#        [ 0.,  1.,  0.],
#        [ 0.,  0.,  1.],
#        [ 1.,  0.,  0.]], dtype=float32)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=10, input_dim=784, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.optimizers.Adam(0.001), metrics=['accuracy'])
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [7]:
history = tf.model.fit(x_train, y_train, batch_size=batch_size, epochs=training_epochs)

Epoch 1/15
600/600 [==============================] - 1s 748us/step - loss: 0.9651 - accuracy: 0.7523
Epoch 2/15
600/600 [==============================] - 0s 751us/step - loss: 0.3584 - accuracy: 0.9041
Epoch 3/15
600/600 [==============================] - 0s 736us/step - loss: 0.3113 - accuracy: 0.9148
Epoch 4/15
600/600 [==============================] - 0s 718us/step - loss: 0.2947 - accuracy: 0.91930s - loss: 0.3045 - 
Epoch 5/15
600/600 [==============================] - 0s 724us/step - loss: 0.2867 - accuracy: 0.9209
Epoch 6/15
600/600 [==============================] - 0s 791us/step - loss: 0.2730 - accuracy: 0.9229
Epoch 7/15
600/600 [==============================] - 0s 779us/step - loss: 0.2712 - accuracy: 0.9240
Epoch 8/15
600/600 [==============================] - 0s 719us/step - loss: 0.2624 - accuracy: 0.9271
Epoch 9/15
600/600 [==============================] - 0s 757us/step - loss: 0.2598 - accuracy: 0.9271
Epoch 10/15
600/600 [==============================] - 0s 711u

In [8]:
predictions = tf.model.predict(x_test)
print('Prediction: \n', predictions)
x_train
score = tf.model.evaluate(x_train, y_train)
print('Accuracy: ', score[1])

Prediction: 
 [[3.0854947e-06 1.0839685e-11 6.8773038e-06 ... 9.9406993e-01
  1.8119765e-05 4.7255188e-04]
 [4.2884616e-04 3.0351871e-06 9.9218374e-01 ... 1.8956023e-17
  4.6852198e-05 6.4791658e-14]
 [1.4948712e-06 9.7973162e-01 1.1377638e-02 ... 8.1720360e-04
  3.1771348e-03 2.5862234e-04]
 ...
 [1.7254518e-08 1.0856394e-08 3.4643426e-06 ... 1.6735143e-03
  8.0414116e-03 2.7988130e-02]
 [2.6636812e-07 4.1726852e-07 2.6214195e-07 ... 1.3975904e-07
  1.0220069e-02 2.4665610e-07]
 [9.3407078e-07 2.5757184e-14 3.2940825e-05 ... 1.0304344e-12
  2.1134674e-08 4.6330516e-11]]
1875/1875 [==============================] - 1s 447us/step - loss: 0.2467 - accuracy: 0.9322
Accuracy:  0.932200014591217


In [9]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])