In [1]:
# hello rnn
import numpy as np
import tensorflow as tf

In [6]:
idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
# x_data = [[0, 1, 0, 2, 3, 3]]  # hihell
y_data = [[1, 0, 2, 3, 3, 4]]  # ihello

num_classes = 5
input_dim = 5 # one-hot size, same as hidden_size to directorly predict one-hot
sequence_length = 6 # |ihello| == 6
learning_rate = 0.1

x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)

y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [8]:
tf.model = tf.keras.Sequential()

# make cell and add it to RNN layer
# input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim
cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(sequence_length, input_dim))
tf.model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))

# single LSTM layer can be used as well instead of creating LSTMCell
# tf.model.add(tf.keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, input_dim), return_sequences=True))

# fully connected layer
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate), metrics=['accuracy'])

# train
tf.model.fit(x_one_hot, y_one_hot, epochs=50)
tf.model.summary()

Epoch 1/50
1/1 [==============================] - 1s 975ms/step - loss: 1.6056 - accuracy: 0.1667
Epoch 2/50
1/1 [==============================] - 0s 3ms/step - loss: 1.4860 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 3ms/step - loss: 1.4026 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 1.3258 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 1.2256 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 1.1012 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 3ms/step - loss: 0.9584 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.8056 - accuracy: 0.6667
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6778 - accuracy: 0.6667
Epoch 10/50
1/1 [==============================] - 0s 3ms/step - loss: 0.5709 - accuracy: 0.8333
Epoch 11/50
1/1 [====================

In [9]:
predictions = tf.model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

[[4.6704029e-04 9.9689865e-01 2.5625373e-03 6.9318514e-05 2.5082925e-06]
 [9.9968648e-01 2.9382176e-05 1.9240958e-04 3.6287613e-05 5.5368215e-05]
 [8.4685555e-05 2.4464463e-03 9.9703038e-01 4.3787344e-04 6.4795569e-07]
 [1.8269503e-04 1.7196835e-06 3.6085135e-04 9.9940932e-01 4.5403242e-05]
 [3.2868554e-04 5.7363472e-06 1.2739607e-04 9.9674618e-01 2.7919547e-03]
 [1.7591927e-04 1.8103246e-06 1.1336892e-06 1.9669433e-03 9.9785417e-01]]
	Prediction str:  ihello
