In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [3]:
nb_classes = 7  # 0 ~ 6

# Convert y_data to one_hot
# 클래스 벡터 (정수)를 이진 클래스 행렬로 변환
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [4]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


In [5]:
history = tf.model.fit(x_data, y_one_hot, epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 814us/step - loss: 2.2293 - accuracy: 0.1588
Epoch 2/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.4686 - accuracy: 0.4553
Epoch 3/1000
4/4 [==============================] - 0s 997us/step - loss: 1.3015 - accuracy: 0.5172
Epoch 4/1000
4/4 [==============================] - 0s 995us/step - loss: 1.1513 - accuracy: 0.5868
Epoch 5/1000
4/4 [==============================] - 0s 997us/step - loss: 1.0637 - accuracy: 0.6591
Epoch 6/1000
4/4 [==============================] - 0s 997us/step - loss: 1.0202 - accuracy: 0.7041
Epoch 7/1000
4/4 [==============================] - 0s 997us/step - loss: 0.9174 - accuracy: 0.8114
Epoch 8/1000
4/4 [==============================] - 0s 999us/step - loss: 0.8251 - accuracy: 0.8329
Epoch 9/1000
4/4 [==============================] - 0s 998us/step - loss: 0.8272 - accuracy: 0.8027
Epoch 10/1000
4/4 [==============================] - 0s 663us/step - loss: 0.7420 - accuracy: 0.8708
E

4/4 [==============================] - 0s 998us/step - loss: 0.2152 - accuracy: 0.9654
Epoch 83/1000
4/4 [==============================] - 0s 665us/step - loss: 0.2104 - accuracy: 0.9604
Epoch 84/1000
4/4 [==============================] - 0s 997us/step - loss: 0.2179 - accuracy: 0.9542
Epoch 85/1000
4/4 [==============================] - 0s 665us/step - loss: 0.2305 - accuracy: 0.9540
Epoch 86/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2096 - accuracy: 0.9717
Epoch 87/1000
4/4 [==============================] - 0s 998us/step - loss: 0.2292 - accuracy: 0.9540
Epoch 88/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1995 - accuracy: 0.9665
Epoch 89/1000
4/4 [==============================] - 0s 998us/step - loss: 0.2234 - accuracy: 0.9540
Epoch 90/1000
4/4 [==============================] - 0s 997us/step - loss: 0.2067 - accuracy: 0.9646
Epoch 91/1000
4/4 [==============================] - 0s 665us/step - loss: 0.2051 - accuracy: 0.9725
Epoch 92

4/4 [==============================] - 0s 665us/step - loss: 0.1519 - accuracy: 0.9692
Epoch 163/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1334 - accuracy: 0.9817
Epoch 164/1000
4/4 [==============================] - 0s 665us/step - loss: 0.1618 - accuracy: 0.9754
Epoch 165/1000
4/4 [==============================] - 0s 670us/step - loss: 0.1423 - accuracy: 0.9817
Epoch 166/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1403 - accuracy: 0.9846
Epoch 167/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1379 - accuracy: 0.9754
Epoch 168/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1261 - accuracy: 0.9879
Epoch 169/1000
4/4 [==============================] - 0s 332us/step - loss: 0.1394 - accuracy: 0.9785
Epoch 170/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1431 - accuracy: 0.9785
Epoch 171/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1393 - accuracy: 0.

4/4 [==============================] - 0s 666us/step - loss: 0.1029 - accuracy: 1.0000
Epoch 243/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0903 - accuracy: 1.0000
Epoch 244/1000
4/4 [==============================] - 0s 665us/step - loss: 0.1061 - accuracy: 1.0000
Epoch 245/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0952 - accuracy: 1.0000
Epoch 246/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0977 - accuracy: 1.0000
Epoch 247/1000
4/4 [==============================] - 0s 665us/step - loss: 0.1134 - accuracy: 0.9846
Epoch 248/1000
4/4 [==============================] - 0s 665us/step - loss: 0.1030 - accuracy: 0.9846
Epoch 249/1000
4/4 [==============================] - 0s 665us/step - loss: 0.1030 - accuracy: 0.9908
Epoch 250/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1019 - accuracy: 1.0000
Epoch 251/1000
4/4 [==============================] - 0s 667us/step - loss: 0.0940 - accuracy: 1.

4/4 [==============================] - 0s 998us/step - loss: 0.0901 - accuracy: 1.0000
Epoch 323/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0651 - accuracy: 1.0000
Epoch 324/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0803 - accuracy: 1.0000
Epoch 325/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0836 - accuracy: 0.9846
Epoch 326/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0826 - accuracy: 1.0000
Epoch 327/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0711 - accuracy: 1.0000
Epoch 328/1000
4/4 [==============================] - 0s 664us/step - loss: 0.0834 - accuracy: 1.0000
Epoch 329/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0804 - accuracy: 1.0000
Epoch 330/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0825 - accuracy: 1.0000
Epoch 331/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0796 - accuracy: 1.

4/4 [==============================] - 0s 1ms/step - loss: 0.0677 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0683 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0653 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0626 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0720 - accuracy: 1.0000
Epoch 407/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0728 - accuracy: 1.0000
Epoch 408/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0622 - accuracy: 1.0000
Epoch 409/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0626 - accuracy: 1.0000
Epoch 410/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0620 - accuracy: 1.0000
Epoch 411/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0678 - accuracy: 1.0000
E

4/4 [==============================] - 0s 998us/step - loss: 0.0547 - accuracy: 1.0000
Epoch 483/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0512 - accuracy: 1.0000
Epoch 484/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0568 - accuracy: 1.0000
Epoch 485/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0598 - accuracy: 1.0000
Epoch 486/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0562 - accuracy: 1.0000
Epoch 487/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0505 - accuracy: 1.0000
Epoch 488/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0511 - accuracy: 1.0000
Epoch 489/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0551 - accuracy: 1.0000
Epoch 490/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0508 - accuracy: 1.0000
Epoch 491/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0532 - accuracy: 1.00

4/4 [==============================] - 0s 665us/step - loss: 0.0468 - accuracy: 1.0000
Epoch 563/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0479 - accuracy: 1.0000
Epoch 564/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0436 - accuracy: 1.0000
Epoch 565/1000
4/4 [==============================] - 0s 996us/step - loss: 0.0496 - accuracy: 1.0000
Epoch 566/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0439 - accuracy: 1.0000
Epoch 567/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0571 - accuracy: 1.0000
Epoch 568/1000
4/4 [==============================] - 0s 999us/step - loss: 0.0518 - accuracy: 1.0000
Epoch 569/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0413 - accuracy: 1.0000
Epoch 570/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0479 - accuracy: 1.0000
Epoch 571/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0472 - accuracy: 1.

4/4 [==============================] - 0s 1ms/step - loss: 0.0387 - accuracy: 1.0000
Epoch 643/1000
4/4 [==============================] - 0s 677us/step - loss: 0.0440 - accuracy: 1.0000
Epoch 644/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0381 - accuracy: 1.0000
Epoch 645/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0399 - accuracy: 1.0000
Epoch 646/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0443 - accuracy: 1.0000
Epoch 647/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0405 - accuracy: 1.0000
Epoch 648/1000
4/4 [==============================] - 0s 678us/step - loss: 0.0398 - accuracy: 1.0000
Epoch 649/1000
4/4 [==============================] - 0s 664us/step - loss: 0.0372 - accuracy: 1.0000
Epoch 650/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0382 - accuracy: 1.0000
Epoch 651/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0394 - accuracy: 1.0000

4/4 [==============================] - 0s 997us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 723/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0382 - accuracy: 1.0000
Epoch 724/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0421 - accuracy: 1.0000
Epoch 725/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0408 - accuracy: 1.0000
Epoch 726/1000
4/4 [==============================] - 0s 676us/step - loss: 0.0383 - accuracy: 1.0000
Epoch 727/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0342 - accuracy: 1.0000
Epoch 728/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0394 - accuracy: 1.0000
Epoch 729/1000
4/4 [==============================] - 0s 985us/step - loss: 0.0430 - accuracy: 1.0000
Epoch 730/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0324 - accuracy: 1.0000
Epoch 731/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0331 - accuracy: 1.

4/4 [==============================] - 0s 665us/step - loss: 0.0359 - accuracy: 1.0000
Epoch 803/1000
4/4 [==============================] - 0s 666us/step - loss: 0.0401 - accuracy: 1.0000
Epoch 804/1000
4/4 [==============================] - 0s 664us/step - loss: 0.0276 - accuracy: 1.0000
Epoch 805/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0391 - accuracy: 1.0000
Epoch 806/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0357 - accuracy: 1.0000
Epoch 807/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0318 - accuracy: 1.0000
Epoch 808/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0322 - accuracy: 1.0000
Epoch 809/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0343 - accuracy: 1.0000
Epoch 810/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0283 - accuracy: 1.0000
Epoch 811/1000
4/4 [==============================] - 0s 652us/step - loss: 0.0378 - accuracy: 1.

4/4 [==============================] - 0s 998us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 883/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0309 - accuracy: 1.0000
Epoch 884/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0263 - accuracy: 1.0000
Epoch 885/1000
4/4 [==============================] - 0s 666us/step - loss: 0.0335 - accuracy: 1.0000
Epoch 886/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0367 - accuracy: 1.0000
Epoch 887/1000
4/4 [==============================] - 0s 677us/step - loss: 0.0343 - accuracy: 1.0000
Epoch 888/1000
4/4 [==============================] - 0s 984us/step - loss: 0.0314 - accuracy: 1.0000
Epoch 889/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0278 - accuracy: 1.0000
Epoch 890/1000
4/4 [==============================] - 0s 667us/step - loss: 0.0329 - accuracy: 1.0000
Epoch 891/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0273 - accuracy: 1.

4/4 [==============================] - 0s 677us/step - loss: 0.0286 - accuracy: 1.0000
Epoch 963/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0301 - accuracy: 1.0000
Epoch 964/1000
4/4 [==============================] - 0s 678us/step - loss: 0.0285 - accuracy: 1.0000
Epoch 965/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0301 - accuracy: 1.0000
Epoch 966/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 967/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0317 - accuracy: 1.0000
Epoch 968/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0230 - accuracy: 1.0000
Epoch 969/1000
4/4 [==============================] - 0s 655us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 970/1000
4/4 [==============================] - 0s 656us/step - loss: 0.0267 - accuracy: 1.0000
Epoch 971/1000
4/4 [==============================] - 0s 665us/step - loss: 0.0322 - accuracy: 1.

In [6]:
# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

[[8.5589732e-04 1.2215050e-03 6.6203149e-03 9.8632622e-01 4.0598614e-03
  3.6146378e-07 9.1585709e-04]] [3]


C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [7]:
# Full x_data test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P