In [8]:
import tensorflow as tf
import numpy as np
import pprint

tf.random.set_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.compat.v1.InteractiveSession()

# Simple Array

In [11]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [12]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


# Shape, Rank, Axis(축)

In [16]:
t = tf.constant([1,2,3,4])
print(t)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [15]:
t = tf.constant([[1,2],
                 [3,4]])
print(t)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [17]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)


In [19]:
[ # axis = -1
    [
        [
            [1,2,3,4],  # axis -> 제일 안쪽에 있는 것이 가장 큰 값
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

# Matmul VS multiply

In [22]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(tf.matmul(matrix1, matrix2))

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


In [25]:
print(matrix1*matrix2)

tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


# Watch out broadcasting

In [26]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(matrix1+matrix2)

tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)


In [27]:
# broadcasting은 shape이 다르더라도 연산을 할 수 있게 해주는 것
# 가능하면 앞뒤 shape을 고려해서 같은 shape 연산을 할 것
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
print(matrix1+matrix2)

tf.Tensor([[5. 5.]], shape=(1, 2), dtype=float32)


In [28]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
print(matrix1+matrix2)

tf.Tensor([[4. 5.]], shape=(1, 2), dtype=float32)


# Random values for variable initializations

In [30]:
print(tf.random.normal([3]))

tf.Tensor([ 0.7706481   0.37335402 -0.05576323], shape=(3,), dtype=float32)


In [31]:
print(tf.random.uniform([2]))

tf.Tensor([0.42134905 0.7339295 ], shape=(2,), dtype=float32)


In [32]:
print(tf.random.uniform([2, 3]))

tf.Tensor(
[[0.909613   0.34968376 0.39626384]
 [0.6574153  0.60619414 0.70691717]], shape=(2, 3), dtype=float32)


# Reduce Mean/Sum

In [33]:
print(tf.math.reduce_mean([1, 2], axis=0))

tf.Tensor(1, shape=(), dtype=int32)


In [35]:
x = [[1., 2.], # axis=1
     [3., 4.]] # axis=-1
    # axis=0

print(tf.math.reduce_mean(x))

tf.Tensor(2.5, shape=(), dtype=float32)


In [36]:
print(tf.math.reduce_mean(x, axis=0))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [37]:
print(tf.math.reduce_mean(x, axis=1))

tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [38]:
print(tf.math.reduce_mean(x, axis=-1))

tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [40]:
print(tf.math.reduce_sum(x))

tf.Tensor(10.0, shape=(), dtype=float32)


In [42]:
print(tf.math.reduce_sum(x, axis=0))

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [43]:
print(tf.math.reduce_sum(x, axis=-1))

tf.Tensor([3. 7.], shape=(2,), dtype=float32)


In [44]:
print(tf.math.reduce_mean(tf.reduce_sum(x, axis=-1)))

tf.Tensor(5.0, shape=(), dtype=float32)


# Argmax with axis

In [45]:
# argmax는 가장 큰 값을 찾아 출력
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)


In [47]:
print(tf.argmax(x, axis=1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


In [48]:
print(tf.argmax(x, axis=-1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


# Reshape, squeeze, expand_dims

In [49]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [50]:
print(tf.reshape(t, shape=[-1, 3]))

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)


In [52]:
print(tf.reshape(t, shape=[-1, 1, 3]))

tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int32)


In [53]:
print(tf.squeeze([[0], [1], [2]]))

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [54]:
print(tf.expand_dims([0, 1, 2], 1))

tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


# One hot

In [55]:
# 자리를 출력
print(tf.one_hot([[0], [1], [2], [0]], depth=3))

tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)


In [56]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(tf.reshape(t, shape=[-1, 3]))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]], shape=(4, 3), dtype=float32)


# Casting

In [57]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [58]:
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


# Stack

In [59]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
print(tf.stack([x, y, z]))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [61]:
print(tf.stack([x, y, z], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Ones like and Zeros like

In [62]:
x = [[0, 1, 2],
     [2, 1, 0]]

print(tf.ones_like(x))

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [63]:
print(tf.zeros_like(x))

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


# Zip

In [67]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [65]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Transpose

In [68]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
